### ISSUE TITLE
Include a minimal or example config.json

### ISSUE THREAD

**Issue by frenata** [EmissarySocial/emissary#179]
Currently running `go run server.go` provokes this error:

`panic: Error reading configuration: ./config.json`

=> `$ touch config.json`

`panic: Invalid configuration file: unexpected end of JSON input `

=> `$ cat "" >> config.json`

```
Factory: received new configuration...
⇨ http server started on [::]:80
{
        "code": 500,
        "location": "server.Factory.start",
        "message": "Error getting attachment original directory",

// etc
```

Either useful defaults (if possible) or a documented minimal config should be provided.

**Comment by benpate** [comment]
Yes. Excellent point. I was concerned that creating a default confit might lead to security issues. Plus, we will always need to have the bc connection info in order to run for real. 

Try running the app with the `go run server.go --setup` flag. This will open a simple confit console where you can enter all the required details and override default values.

**Comment by benpate** [comment]
Thanks, @frenata - I'm closing this one for now because I think we've answered this question, and have added links so that future devs can find this more quickly.  Please let me know how your research goes.  I'm happy to help you get this running in your own environment.

**Comment by frenata** [comment]
Yah I've gotten further. There are definitely some hiccups with putting together a valid config via `--setup` that I'll try to synthesize and write-up. Would you be open to accepting a model `config.json` with clear <FILL_IN_HERE> material where the user needs to make a decision? The mongodb url is an obvious case, for instance.

Separately I'm looking at a minimal `docker-compose.yaml` that will boot everything in a working environment.

**Comment by benpate** [comment]
Yes, I think this makes sense, too.  And perhaps we have the server detect the "default" config, and respond with a message telling the dev to run in --setup mode first.  In case you still need it, here's my current setup:

```json
{
	"domains": [
		{
			"domainId":"635c203b0a59bf27b37e3268",
			"label":"Test Database",
			"hostname":"localhost",
			"connectString":"mongodb://127.0.0.1",
			"databaseName":"emissary_localhost",
			"smtp": {
				"hostname":"smtp.mailtrap.io",
				"username":"---",
				"password":"---",
				"port": 465,
				"tls": false
			},
			"owner": {
				"displayName":"Ben Pate",
				"username":"benpate",
				"emailAddress":"---",
				"phoneNumber":"---",
				"mailingAddress":"---"
			}
		},
	],
	"providers": [],
	"templates": [
		{
			"adapter":"FILE",
			"location":"./_embed/templates"
		}
	],
	"emails": [
		{
			"adapter":"FILE",
			"location":"./_embed/emails"
		}
	],
	"attachmentOriginals": {
		"adapter":"FILE",
		"location":".emissary/attachmentOriginals"
	},
	"attachmentCache": {
		"adapter":"FILE",
		"location":".emissary/attachmentCaches"
	},
	"certificates": {
		"adapter":"FILE",
		"location":".emissary/certificates"
	},
	"adminEmail":""
}
```

**Comment by benpate** [comment]
Regarding Docker: Yes, 100%.  It's something I want to do, but I have exactly zero experience with Docker.  If you do, feel free to add a pull request!

**Comment by benpate** [comment]
I just pushed a change that includes a default config.json along with better error messaging around using this default file.  Hope this helps you out!

**Comment by frenata** [comment]
> Regarding Docker: Yes, 100%. It's something I want to do, but I have exactly zero experience with Docker. If you do, feel free to add a pull request!

Yah, I have a mostly working setup and will PR once I clean it up a bit.

The config is helpful on a few points that I couldn't work out for myself, but once I found `_embed` things made much more sense.

**Comment by benpate** [comment]
I've just uploaded a big change to the startup and configuration.  Hopefully, this alleviates a lot of the issues you had in getting started.  I'm going to close this issue for now, but please let me know if you'd like more help digging into Emissary.  I'm really invested in making this work for everyone :)
