### ISSUE TITLE
Allow the PORT to be specified via config

### ISSUE THREAD

**Issue by frenata** [EmissarySocial/emissary#182]
https://github.com/EmissarySocial/emissary/blob/a3805ed4c88305296d51848f4eecc01ab300e8f4/server.go#L261

This shouldn't be hard-coded to 80, but instead should use a configurable port and probably default to a more common development port like 8080.

**Comment by benpate** [comment]
Yes.  This is an excellent idea.  I'm tied up all day today, but will try to add this as soon as I get a chance.

**Comment by benpate** [comment]
Since Emissary loads the configuration files asynchronously, this change turns out to be more complicated than I originally thought.  It's still an important change, so I *am* working on it.  It's just going to require more refactoring than I had hoped :(

**Comment by frenata** [comment]
I'm happy to assist if you point me the right direction.

**Comment by benpate** [comment]
And I'm super-grateful for any contributions you'd like to make.  Looking at this might help you dig into the server a bit more -- though it's not a critical piece and I don't want to frustrate you on your first task so please let me know if you feel like you're banging your head on a wall..

Here's the straightforward approach that will get it (mostly) working now:

1) Add HTTPPort and HTTPSPort values to the [main config file map](https://github.com/EmissarySocial/emissary/blob/8de3e94d4f1f145cce3680833ffedb0efe816fa4/config/config.go#L19)

2) Add the config as a new parameter to the [startHttp](https://github.com/EmissarySocial/emissary/blob/8de3e94d4f1f145cce3680833ffedb0efe816fa4/server.go#L258) and [startHttps](https://github.com/EmissarySocial/emissary/blob/8de3e94d4f1f145cce3680833ffedb0efe816fa4/server.go#L248) functions

3. Use the new configured values in the "start" functions.  And if the value is zero, skip that protocol entirely.

The harder part will be restarting these services on new ports in case the configuration changes.  How do you feel about "getting it working" first, then talking about the second step?

**Comment by frenata** [comment]
Sure. I also think it's a reasonable choice to say "Emissary doesn't support live reloading of port changes".

**Comment by benpate** [comment]
Yes.  That would be much easier all around :)

**Comment by benpate** [comment]
It's been a while on this issue, but the current build (finally) supports this and includes settings in the admin tool to update the HTTP and HTTPS ports.
