### ISSUE TITLE
Needs go 1.21

### ISSUE THREAD

**Issue by andrewmoise** [EmissarySocial/emissary#373]
It looks to me like emissary can't compile without at least version 1.21:

```
../go/pkg/mod/github.com/benpate/sherlock@v0.7.1/actor-feed-icon.go:4:2: package slices is not in GOROOT (/usr/lib/go-1.19/src/slices)
```

Maybe the docs should be adjusted to say 1.21 instead of 1.19?

**Comment by benpate** [comment]
Good catch.  Yes.  Some of the dependencies changes, which bumped up the required version of Go.  I'm updating the webstie now.

And I'll need to bump it forward with 1.23 (probably) -- once Go Range Functions become stable, there are lots of places where channels could be refactored into something more efficient.
