### ISSUE TITLE
doing petitions to get posts without proper signature in some cases

### ISSUE THREAD

**Issue by gabboman** [EmissarySocial/emissary#459]
Hello! what the title says.

I am the creator of wafrn and I got this on my logs
<img width="705" alt="Captura de pantalla 2024-07-19 a las 22 22 31" src="https://github.com/user-attachments/assets/f4091815-4adc-4028-ba6c-a40bc618794c">

I am about to enforce auth fetch by default and stuff... so yeah.

Also your ssl certificate for emissary dot social is wrong

**Comment by benpate** [comment]
Hey.. thanks for the heads up.  It looks like there are a few separate issues here:

0) I'm not familiar with this error message, so I'm assuming that it's your app alerting you to an unsigned request from Emissary. Is this correct?  I don't want to troubleshoot too much until I'm confident that I'm not barking up the wrong tree.

1) Emissary doesn't yet send "authorized fetches" -- which is true.  I know I'm going to need to do it soon, but Emissary's (unique?) caching architecture has left me with just enough questions that I've avoided doing this until I *really had to* and I also *knew the right way to solve it*.  So, thanks for the heads up on this.  I'll push this higher up in my to-do list.

2) There's something funny with the emissary.social domain right now.  I think I misconfigured the DNS when I migrated to a new set of servers.  I'm not really using it until I get out of the "development phase" (whatever that means) so I've kind of neglected the DNS.  But, thanks for the heads up.  I'll have that domain running soon.

3) Not an issue, just a shout out for https://github.com/gabboman/wafrn -- I'm checking out your site and it looks pretty cool.  Well done!

**Comment by gabboman** [comment]
correct, its my logs. signature to get posts is important.

we have switched to a system that every time a remote instance asks for a post we store it on the database. that way we know what instances have a post for the time of deleting them or for edits

**Comment by benpate** [comment]
Closing the loop on this, I've recently posted a series of updates to Emissary that adds an Instance Actor to support Authorized Fetch.  So, those errors you received before should clear up.

Thanks again for letting me know about this, and please tell me if you have any other trouble connecting to/from Emissary domains.
